CREATE TABLE Agency (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    descr TEXT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Client (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    fio TEXT NOT NULL,
    money REAL NOT NULL,
    town TEXT,
    agency INTEGER,
    FOREIGN KEY (agency) REFERENCES Agency(id)
);

CREATE TABLE EstateType (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL
);

CREATE TABLE Estate (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    address TEXT NOT NULL,
    square REAL NOT NULL,
    rooms_cnt INTEGER NOT NULL,
    posted_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    agency INTEGER,
    type INTEGER,
    FOREIGN KEY (agency) REFERENCES Agency(id),
    FOREIGN KEY (type) REFERENCES EstateType(id)
);
