CREATE TABLE Agency (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    descr TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Client (
    id SERIAL PRIMARY KEY,
    fio VARCHAR(255) NOT NULL,
    money NUMERIC(12, 2) NOT NULL DEFAULT 0.00,
    town VARCHAR(100),
    agency INTEGER REFERENCES Agency(id) ON DELETE SET NULL
);

CREATE TABLE EstateType (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL
);

CREATE TABLE Estate (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    address TEXT NOT NULL,
    square NUMERIC(10, 2) NOT NULL,
    rooms_cnt INTEGER NOT NULL,
    posted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    agency INTEGER REFERENCES Agency(id) ON DELETE SET NULL,
    type INTEGER REFERENCES EstateType(id) ON DELETE SET NULL
);
